"""Initial schema

Revision ID: 02b7d40971cb
Revises: 
Create Date: 2026-06-25 23:08:18.783351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b7d40971cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reviews', 'visits', ['visit_id'], ['id'])
    op.create_foreign_key(None, 'visits', 'users', ['technician_id'], ['id'])
    op.create_foreign_key(None, 'visits', 'users', ['client_id'], ['id'])
    op.create_foreign_key(None, 'visits', 'service_requests', ['service_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    # ### end Alembic commands ###
